- {configure: './configure --prefix={installdir}/{dirname}', depends: maven, dirname: '{name}-{version}',
  make: mvn -DskipTests clean package, url: 'http://www.interior-dsgn.com/apache/spark/spark-{version}/spark-{version}.tgz',
  version: 1.3.1}

