- {configure: './configure --prefix={installdir}/{dirname} --with-apr={deploydir}',
  dirname: '{name}-{version}', url: 'http://apache.spinellicreations.com//apr/apr-util-{version}.tar.gz',
  version: 1.5.4}

