- configure: CXX={deploydir}/bin/g++-{gcc-version} CC={deploydir}/bin/gcc-{gcc-version}
    ./configure --prefix={installdir}/{dirname}
  depends:
  - [gcc, 5.3.0]
  dirname: '{name}-{version}'
  url: http://www.cmake.org/files/v3.2/{dirname}.tar.gz
  version: 3.2.2
- configure: CXX={deploydir}/bin/g++-{gcc-version} CC={deploydir}/bin/gcc-{gcc.version}
    ./configure --prefix={installdir}/{dirname}
  depends:
  - [gcc, 5.3.0]
  dirname: '{name}-{version}'
  url: http://www.cmake.org/files/v3.2/{dirname}.tar.gz
  version: 2.8.2

