- configure: ./configure --prefix={installdir}/{dirname} --with-curses={deploydir}
  depends: [ncurses]
  dirname: '{name}-{version}'
  url: ftp://ftp.gnu.org/gnu/readline/readline-{version}.tar.gz
  version: '6.3'

