{apache-maven: 3.3.3, apache-spark: 1.3.1, binutils: '2.25', bison: 3.0.4, clang: 3.5.0,
  cloog: git, cmake: 3.2.2, flex: 2.5.39, gcc: 5.3.0, gmp: 6.0.0, isl: '0.13', libelf: 0.8.13,
  libtool: 2.4.6, lua: 5.1.5, motif: 1.2.8, mpc: 1.0.3, mpfr: 3.1.2, nano: 2.4.1,
  ncurses: '5.9', ppl: '1.1', readline: 1.2.8, scons: 1.2.8, shtool: 2.0.8, texinfo: '5.2',
  tolua: 1.2.8, zlib: 1.2.8}

